# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Microservice-API' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Microservice-API
  pod 'Alamofire'
  pod 'SwiftyJSON'
  target 'Microservice-APITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Microservice-APIUITests' do
    # Pods for testing
  end

end
